- README.md
Updated url after transfer of repository
> Fix build status icon

- src/pydap/tests/test_cas_esgf.py
- src/pydap/tests/test_cas_urs.py
This is a simple PR to clean-up auth tests a bit more.
> Cleaner assertion testing in auth tests

- src/pydap/cas/get_cookies.py
This is a rebased version of #40.
> Fix mechanicalsoup browser clean-up with error

- src/pydap/parsers/das.py
- src/pydap/tests/test_parsers_das.py
This PR solves #75. It introduces a more stringent DAS test.
> Fix attributes parser error raised in #75

- .travis.yml
- setup.py
- src/pydap/tests/test_handlers_lib.py
- src/pydap/tests/test_responses_ascii.py
- src/pydap/tests/test_responses_das.py
- src/pydap/tests/test_responses_dds.py
- src/pydap/tests/test_responses_dods.py
- src/pydap/tests/test_responses_html.py
- src/pydap/tests/test_responses_version.py
- src/pydap/tests/test_webtest.py
- src/pydap/tests/test_wsgi_app.py
- src/pydap/tests/test_wsgi_functions.py
- src/pydap/tests/test_wsgi_ssf.py
This PR converts testing to ``pytest``. It does not modify other aspects of testing and further work will have to be done to modernize tests.
> Basic pytest compatiblity

- docs/client.rst
- src/pydap/model.py
- src/pydap/tests/test_model.py
This adresses #43. Tests are included and everything appears to be working fine.
> Add NumPy-like properties to GridType and length to StructureType

- src/pydap/handlers/dap.py
- src/pydap/tests/test_handlers_dap.py
This is a weird bug that I only picked up when working on a different PR. Seems straighforward.
> Fix a bug where the iteration does not replace previous_chunk

- .travis.yml
- NEWS.md
- setup.py
> Deprecate python 3.3

- docs/conf.py
- docs/index.rst
- docs/server.rst
Fixes #46 
Rewrote the Apache section, rewrote the uwsgi section, removed the paste references, added
instructions for using the standalone server script, added a Flask section, added
docker links.
> Update the server docs

- docs/client.rst
> Fix title level inconsistency

- src/pydap/handlers/csv/__init__.py
- src/pydap/handlers/lib.py
- src/pydap/lib.py
- src/pydap/model.py
- src/pydap/parsers/__init__.py
- src/pydap/tests/test_model.py
- src/pydap/tests/test_responses_error.py
- src/pydap/wsgi/app.py
- src/pydap/wsgi/ssf.py
To fix #121, IndexError must be a valid exception. This comes along because different servers have slightly different behaviours wrt to GridTypes.
> Fixes #121, fixes deprecation warnings and incorporates flake8 changes

- setup.py
> add requests to core dependencies (#145) (#120)

- src/pydap/handlers/dap.py
- src/pydap/handlers/lib.py
- src/pydap/parsers/dds.py
- src/pydap/tests/test_handlers_dap.py
This PR allows the handling of gzipped responses. In doing so, it introduces the possibility of providing a gzipped response in ``BaseHandler``.
> Handle gzipped responses (Solves #126)

- src/pydap/tests/test_wsgi_app.py
- src/pydap/wsgi/app.py
- src/pydap/wsgi/templates/catalog.xml
- src/pydap/wsgi/templates/index.html
> add support for THREDDS Catalog XML (#136)

- .travis.yml
- setup.py
- src/pydap/cas/esgf.py
- src/pydap/pycompat.py
- src/pydap/responses/dods.py
- src/pydap/tests/test_iter_data.py
Supersedes #182 by @tomkralidis.
> Fix Travis CI

- src/pydap/handlers/netcdf/__init__.py
> Avoid applying scale factor for consistency with dtype

- src/pydap/responses/das.py
- src/pydap/tests/datasets.py
- src/pydap/tests/test_responses_das.py
> Do not yield faulty DAS lines

- src/pydap/handlers/netcdf/__init__.py
I believe this replicates the desired behavior described by @neaptide  in #128 as a "hack" solution. I do not know the implications here regarding how the handler will operate, but simply replicated the described behavior.
> Handle KeyErrors as described in issue #128

- src/pydap/client.py
- src/pydap/handlers/dap.py
https://data.csiro.au/dap/ws/v2/collections is an example I've found.
> Add 'default_charset' to open_url, for servers that don't specify it but serve utf-8

- src/pydap/handlers/dap.py
Closes https://github.com/pydap/pydap/issues/224
Sorry to bother again @tomkralidis
> fix pos arg

- .github/workflows/python.yml
- src/pydap/tests/test_server_devel.py
adding GitHub actions CI workflow
> adding GitHub actions CI workflow

- README.md
- src/pydap/lib.py
- src/pydap/responses/dods.py
- src/pydap/tests/test_responses_dods.py
Fixes #232 
Fixes deprecation warning about tostring/tobytes.
> fixed tostring warnings

- src/pydap/client.py
> Pass timeout and session to server side functions (called subsequently after open_url)

- .github/workflows/python_macos.yml
Fixes #254 
adding macos to GitHub CI
> adding macos to GitHub CI

- src/pydap/handlers/lib.py
- src/pydap/wsgi/app.py
Don't try and create a handler instance for each file in the list (which is expensive).
Fixes Issue #208
> Fix to speed up directory listings.

- src/pydap/__init__.py
Part of #240 
changed version to 3.3.0
> changed version to 3.3.0

- README.md
Fixes #235 
Now linking to docs on gh-pages branch.
> fixing documentation links in README

- src/pydap/parsers/dmr.py
- src/pydap/tests/data/dmrs/SimpleGroup.dmr
- src/pydap/tests/datasets.py
- src/pydap/tests/test_parsers_dmr.py
- src/pydap/tests/test_responses_dmr.py
> Parse NaN attribute values on DMR (DAP4)

- .github/workflows/publish_to_pypi.yml
> Include additional checks to PYPI gh actions

- docs/5_minute_tutorial.ipynb
- docs/client.ipynb
- docs/contribute/contr_cod.md
- docs/contribute/contr_docs.md
- docs/how_to_install.md
- docs/responses.rst
- docs/server.rst
> Improve docs description of Constraint Expressions (include shared dimensions)

- src/pydap/model.py
- src/pydap/parsers/dmr.py
- src/pydap/responses/dmr.py
- src/pydap/tests/datasets.py
- src/pydap/tests/test_parsers_dmr.py
> Set dimensions at Group level

- .github/workflows/run_tests_macos.yml
- .github/workflows/run_tests_ubuntu.yml
- README.md
- ci/environment.yml
- docs/contribute/contr_cod.md
- docs/contribute/contr_docs.md
- docs/environment.yml
- docs/how_to_install.md
> Docs update

- src/pydap/handlers/netcdf/__init__.py
- src/pydap/parsers/dmr.py
- src/pydap/tests/test_handlers_netcdf.py
> allow repeated named dimensions

- docs/notebooks/SWOT.ipynb
on a local environment.~ Test are not needed. Change to documentation only. Notebook work well on my local machine.
> change variable to plot and decode

- ci/environment.yml
> Remove whitespace on ci/env file

- src/pydap/parsers/dmr.py
- src/pydap/tests/test_parsers_dmr.py
> Parse attribute elements with atomic types on root

- docs/NEWS.md
Update news for soon to be new minor release
> update news for new release

- src/pydap/parsers/dmr.py
- src/pydap/tests/test_parsers_dmr.py
> escape empty white spaces in names of Groups/Variables

- src/pydap/parsers/das.py
- src/pydap/tests/test_client.py
- src/pydap/tests/test_parsers_das.py
> flattens global attributes `NC_GLOBAL` and `DODS_EXTRA` inherited from das parser

- src/pydap/client.py
- src/pydap/handlers/dap.py
- src/pydap/tests/test_client.py
> sets `output_grid=False` as default

- docs/en/Q1.ipynb
- docs/en/Q3.ipynb
- docs/en/Q4.ipynb
More last minute changes - to improve navigation of documentation
> adds an anchor to ease navigation + typos

- docs/build.sh
> creates redirects

- .github/workflows/run_tests_macos.yml
- .github/workflows/run_tests_ubuntu.yml
> add python 3.13 to testing

- src/pydap/parsers/dmr.py
on a local environment.~ I do not thing extra testing is needed. There is no new feature - just migrating code from one place no another
> set global dims when initating the dataset

- src/pydap/model.py
- src/pydap/parsers/dds.py
- src/pydap/responses/dds.py
- src/pydap/responses/dmr.py
- src/pydap/tests/datasets.py
- src/pydap/tests/test_model.py
- src/pydap/wsgi/functions.py
> update BaseType`s reference to dimensions in DAP2

- src/pydap/client.py
- src/pydap/tests/test_client.py
> fix test warn

- pytest.ini
- src/pydap/handlers/dap.py
- src/pydap/lib.py
- src/pydap/model.py
- src/pydap/tests/test_handlers_dap.py
- src/pydap/tests/test_net.py
> String arrays

- src/pydap/client.py
- src/pydap/handlers/dap.py
- src/pydap/lib.py
- src/pydap/model.py
- src/pydap/tests/test_handlers_dap.py
- src/pydap/tests/test_open_dap4_url.py
…d warn
on a local environment.~ are being (slightly) changed for this behavior
> Enforce `checksums=True`, but expose option to users

- src/pydap/handlers/dap.py
- src/pydap/lib.py
- src/pydap/model.py
- src/pydap/net.py
- src/pydap/tests/test_client.py
- src/pydap/tests/test_lib.py
- src/pydap/tests/test_open_dap4_url.py
> Improves memory management

- src/pydap/lib.py
- src/pydap/tests/test_lib.py
Makes sure data after batch has right shape. Mostly relevant for use within xarray's backend
- ~[ ] Closes an already existing opened issue #xxxx for fixing a bug, requesting
a new feature, etc.~
> add a data checker 
