pydap/pydap

.travis.yml, docs/client.rst, setup.py, src/pydap/cas/esgf.py, src/pydap/cas/get_cookies.py, src/pydap/cas/urs.py, src/pydap/client.py, src/pydap/handlers/dap.py, src/pydap/net.py, src/pydap/tests/test_cas_esgf.py, src/pydap/tests/test_cas_urs.py
This PR is a solution to #20. It uses a very different approach that avoids monkey patching. At the moment this method provides facilities for both URS NASA EARTHDATA authentication and ESGF authentication.
A variant of this PR has been actively used in [laliberte/netcdf4_pydap](https://github.com/laliberte/netcdf4_pydap) and stress tested with [laliberte/cdb-query](https://github.com/laliberte/cdb-query). The idea is to use a ``requests.Session()`` object to carry around cookies from the authentication service. It has many advantages:
1. The ``requests.Session()`` object is thread safe.
2. The ``requests.Session()`` object can be used in other applications, for example if one simply wants to ``wget`` the file using the same authentication. This is a natural workflow with the THREDDS …
=> A method for ESGF / URS authentication

src/pydap/lib.py, src/pydap/tests/test_handlers_dap.py
This PR fixes a bug that arises when a ``pydap`` array is sliced and the ``slice.stop`` integer is larger than the dimension length.
=> A bug fix in fix_slices

.travis.yml, docs/client.rst, src/pydap/client.py, src/pydap/handlers/dap.py, src/pydap/model.py, src/pydap/tests/test_cas_esgf.py, src/pydap/tests/test_cas_urs.py
This PR solves a bug on ESGF servers whereas retrieving coordinates of grid variables would  uncover a memory leak on the OPENDAP server. The solution proposed here is to provide a boolean option ``open_url(..., output_grid=False)`` that disables the retrieval of these coordinates. This essentially reverts to the behavior of ``pydap 3.1.1`` and is more akin to the behavior of ``netcdf4-python``. 
Considering that many use cases for ``pydap`` involve the ESGF, I would consider this bug fix high priority (it certainly is for me: without it ``pydap 3.2.0`` is essentially useless for me). I am open to a different approach / another name for ``output_grid``, as long as there is a high level method to disable the grid retrieval.
=> Fix a bug with ESGF OPENDAP servers

src/pydap/handlers/dap.py, src/pydap/tests/test_handlers_dap.py
This fixes #41. @taehold was right that a ``reshape`` was missing.
=> Ensure that arrays of strings have the correct shape

src/pydap/tests/test_cas_esgf.py, src/pydap/tests/test_cas_urs.py
This PR makes the auth fail when the credential environment variables are not set.
The method used here tests whether a test_url gives a 200 response.
=> Auth tests fail when credentials are not specified.

src/pydap/parsers/das.py
I encountered some EPIC-formatted data that contains '-nan' values in some attributes. This PR fixes a problem where pydap would raise a *** ValueError: malformed string Exception.
=> Treat '-nan' attribute value as a nan value

docs/client.rst, src/pydap/cas/esgf.py, src/pydap/cas/get_cookies.py, src/pydap/cas/urs.py, src/pydap/net.py, src/pydap/tests/test_cas_esgf.py, src/pydap/tests/test_cas_urs.py
This PR fixes recent problems with the URS authentication.
The new implementation is based more closely on the ``requests`` library and should be much more robust in the future.
=> Fix to URS authentication

src/pydap/__init__.py, src/pydap/model.py, src/pydap/tests/test_pydap.py
This PR makes two minor fixes that are necessary to ensure tests are working:
1. Makes a copy of ``data`` when a structure is sliced with multiple names. This prevents the FutureDeprecationWarning from affecting ``pydap``.
2. Removes test for ``__doc__``. After extensive testing, it seems that python 3.5 always returns ``None``. For this reason and because it prevents a successful build I think it should be removed. It would also fix #45
=> Fix tests and prevent unintended behaviour in numpy DeprecationWarning

.travis.yml, setup.py
@rsignell-usgs reported issues on Widnows when trying to use `pydap`.
See https://gist.github.com/rsignell-usgs/7c9cf9f88a2f0c920c1a4ee7d7eaf601
This PR crates a `server_extras` entry to allow `pydap` to be installed, and usable without, `gunicorn` present.
=> Do not require gunicorn for a vanilla install

src/pydap/handlers/dap.py
URLs like the one below,
```python
url = 'http://geoport-dev.whoi.edu/thredds/dodsC/estofs/atlantic'
ds = open_url(url)
```
do not have a charset and will fail. It seems that it is safe to set a default to `utf-8`.
=> Default charset to 'utf8'

MANIFEST.in
The test suite provided within the release tarball cannot be run successfully without the data. Closes #54
=> Add the test data to the release tarball

setup.py
It is provided by `functools` for Python 3.5 onwards. Successfully validated on Debian Stretch (Python 3.5.3).
=> Require singledispatch for Python 3.4 or earlier

src/pydap/__init__.py, src/pydap/cas/get_cookies.py, src/pydap/client.py, src/pydap/handlers/dap.py, src/pydap/handlers/lib.py, src/pydap/lib.py, src/pydap/model.py, src/pydap/parsers/__init__.py, src/pydap/parsers/das.py, src/pydap/parsers/dds.py, src/pydap/responses/ascii.py, src/pydap/responses/das.py, src/pydap/responses/dds.py, src/pydap/responses/dods.py, src/pydap/responses/error.py, src/pydap/responses/html/__init__.py, src/pydap/responses/lib.py, src/pydap/responses/version.py, src/pydap/tests/test_handlers_lib.py, src/pydap/tests/test_pydap.py, src/pydap/wsgi/app.py, src/pydap/wsgi/functions.py, src/pydap/wsgi/ssf.py
This PR builds upon #55 to ensure that tests are successful.
This PR converts all imports to explicit relative imports. This makes it possible to include a fork of ``pydap`` as a submodule in another project. It is also much more robust as it prevents potential namespace collisions. Apart for the internal machinery, this PR should not change anything to the current ``pydap`` compatibility and capabilities.
=> Convert all imports to explicit relative imports

setup.py, src/pydap/handlers/dap.py, src/pydap/handlers/lib.py, src/pydap/model.py, src/pydap/parsers/dds.py, src/pydap/tests/test_handlers_dap.py
This PR fixes #6. This code should now work:
```
dataset = open_url('http://oos.soest.hawaii.edu/erddap/griddap/NCEP_Global_Best')
tmpsfc = dataset['tmpsfc']
tmpsfc[0, :, :]
```
This code also makes it possible to solve #76. The way I see it, it will only require a few tweaks to allow these types of links.
=> Parse dods response to handle ERDDAP servers

setup.py
`scipy` is only needed transitively by `gsw` (upstream made this dependency [optional](https://github.com/TEOS-10/python-gsw/commit/2fb1ab7518e2797e690c895a8d501e60f368b64d) since the last release).
=> Remove scipy from testing requirements

.travis.yml, setup.py
This PR completely removes ``scipy`` from testing following the publication of version 3.0.6 of ``gsw`` on [PyPI](https://github.com/TEOS-10/python-gsw/issues/41). This speeds up our builds significantly, hurray! Also, it closes #84.
=> Remove scipy from travis-ci to close #84

src/pydap/model.py
This PR fixes #42. It does not break any tests so I don't see why we would not provide this backward-compatibility.
What do you think @jameshiebert ?
=> Give default name to model components to fix #42

src/pydap/handlers/lib.py, src/pydap/tests/test_iter_data.py
This PR reintroduces the previously skipped ``IterData`` tests. It introduces small modifications to the ``IterData`` structure (namely how it outputs datatypes).
Also, I have converted the reintroduced tests to ``pytest`` format.
=> Reintroduce IterData tests

setup.py
This solves #100, at least temporarily, by pinning ``gsw`` version to 3.0.6.
=> Pin gsw to version 3.0.6 for support for python 2.7, 3.4

setup.py, src/pydap/net.py, src/pydap/tests/test_net.py
This PR fixes issue #98. It solves it by allowing redirects even when no ``session`` is passed to the ``GET`` command. I've also added some testing to prevent regressions.
=> Allow redirects even without credentials

src/pydap/handlers/lib.py, src/pydap/parsers/__init__.py, src/pydap/parsers/das.py, src/pydap/parsers/dds.py, src/pydap/tests/test_handlers_lib.py, src/pydap/tests/test_parsers.py, src/pydap/tests/test_responses_error.py, src/pydap/wsgi/functions.py, src/pydap/wsgi/ssf.py
This PR prevents a deprecation warning in python 3.6 about escape characters. It removes the warning by explicitly converting all strings with escaped characters to string literals ``r'...'``.
=> Prevent a Deprecation Warning in 3.6

setup.py, src/pydap/server/devel.py, src/pydap/tests/test_server_devel.py
This PR provides the development test server from PR #34. The goal here is dissociate the merging of the CSV handler from the introduction of a test server.
=> Simple devel test server

.travis.yml, setup.py, src/pydap/handlers/netcdf/__init__.py, src/pydap/model.py, src/pydap/net.py, src/pydap/tests/test_handlers_netcdf.py
This PR merges the previously disjoint netCDF handler into the main distribution.
As in #34 , the main goal here to provide a handler so that one could implement more advanced unit tests that would cover a more extensive array of use cases. One of my goal here is to provide a good testing environment to develop a ``netCDF4``-like client API for pydap as in [netcdf4_pydap](github/laliberte/netcdf4_pydap).
Unlike in #34, this PR introduces a major dependency, namely ``netCDF4``. However, I feel that since it is an optional pre-requisite it might not cause too much trouble.
I hope this can be useful to someone other myself.
=> Merging netCDF handlers

.travis.yml, docs/client.rst, setup.py, src/pydap/cas/get_cookies.py, src/pydap/tests/test_cas_esgf.py, src/pydap/tests/test_cas_urs.py
This PR fixes the authentication scheme to ensure that CEDA openids are working. It also includes a test to prevent regressions.
This fix replaces the ``mechanicalsoup`` dependency with ``beautifulsoup4``. I think this is for the best since ``beautifulsoup4`` is a generally better maintained package.
=> Fix CEDA openid authentication

setup.py, src/pydap/cas/get_cookies.py
This PR fixes #102. It switches ``html5lib`` to ``lxml`` parser and adds ``lxml`` as a dependency in ``setup.py``. This PR also removes ``scipy`` from dependencies. It must have been re-added by mistake (#90).
=> Hot fix to ensure that CEDA openid fix is working

src/pydap/client.py, src/pydap/handlers/dap.py, src/pydap/lib.py, src/pydap/parsers/das.py, src/pydap/parsers/dds.py, src/pydap/responses/das.py, src/pydap/responses/dds.py, src/pydap/responses/dods.py, src/pydap/tests/datasets.py, src/pydap/tests/test_client.py, src/pydap/tests/test_handlers_dap.py, src/pydap/tests/test_parsers_dds.py, src/pydap/tests/test_responses_das.py, src/pydap/tests/test_responses_dds.py, src/pydap/tests/test_responses_dods.py
This PR follows #91 and aims to close #5. It provides a much more systematic way of encoding data to DODS and decoding DODS data to Numpy. Along the way, it clarifies the Byte usage. In DAP2, there is no Byte type, only Unsigned Byte type. This means that to encode Signed Bytes to DODS, they have to be upconverted to Int16 and then encoded to DODS. With this PR this is now done transparently.
=> Ensure Byte use is consistent with DAP2 standards (solves #5)

docs/client.rst, src/pydap/client.py, src/pydap/handlers/dap.py, src/pydap/lib.py, src/pydap/net.py, src/pydap/tests/test_server_devel.py
This PR follows #92 and supersedes #37. It introduces a simple timeout feature that enables a user to use ``open_urls`` and ``open_dods`` with an optional ``timeout`` argument. When opened this way, urls will raise an error is the server fails to respond is fewer seconds than specific by the ``timeout`` argument.
=> Add a timeout option to open_urls and open_dods

setup.py
`unittest.mock` is available since Python 3.3
=> Do not require mock for Python 3.3 or later

README.md
The README linked to http://pydap.readthedocs.io/en/latest/server.html when it should have linked to http://pydap.readthedocs.io/en/latest/client.html.
=> Fix bad link in README

src/pydap/handlers/dap.py, src/pydap/lib.py, src/pydap/tests/test_lib.py, src/pydap/tests/test_responses_ascii.py
Unit tests were failing in Python 3.5 because for some reason `encode(numpy.array('1', dtype='<U1'))` was returning `1` instead of `"1"`. I fixed it with an explicit check, though it would be good to refactor the `encode` function to make it more robust.
I also fixed a deprecation warning, using `frombuffer` instead of `fromstring`.
=> Fix unit tests in Python 3.5

src/pydap/net.py
I had o problem loading data from the Global Forecast System (GFS). It raised a UnicodeDecodeError exception, which after a while I figured out it happens because the data is gzipped. I came up with a solution modifying the `GET` function in the `net` module, adding `response.decode_content()`.
=> Fix gzip compression (#126)

docs/client.rst
A couple of minor doc fixes in `client.rst`:
1. The Timeout section had a couple of urls without ending `'`.
2. Removed a citation that I think is unnecessary at best and offensive at worse.
3. My editor stripped ending whitespace from a handful of lines.
=> minor client doc fixes

setup.py
This is the simple fix recommended by @jblarsen  in https://github.com/pydap/pydap/issues/129#issue-238923262.
fixes #129
fixes #165
Basically, it seems like the netcdf handler entry point was not being installed by `setup.py`. So when `load_handlers()` gets called (https://github.com/pydap/pydap/blob/master/src/pydap/handlers/lib.py#L43), no netcdf handler was being found. Consequently, when I tried to run a server
```
pydap --data /path/with/netcdf/files
```
The netcdf files were not being handled correctly.
Contrary to what the [docs say](http://pydap.org/en/latest/handlers.html#installing-data-handlers), the following does not seem to properly set up the entry point:
```
$ pip install Pydap[handlers.netcdf]
```
I just get
```
Requirement already satisfied: Pydap[handlers.netcdf] in …
```
=> add netcdf handler entry point

.travis.yml
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
Follow on from https://github.com/pydap/pydap/pull/192
=> `sudo` is no longer needed

src/pydap/client.py, src/pydap/handlers/dap.py
Follows on from https://github.com/pydap/pydap/issues/196
I believe in https://github.com/pydap/pydap/pull/222 the charset arg (named `default_charset`) had a default value in the functions (`get_charset` and `safe_charset_text`) which weren't getting overridden in the high level `__init__` args.
Hence
```
url = "https://thredds.ucar.edu/thredds/dodsC/grib/NCEP/GFS/Global_0p25deg/GFS_Global_0p25deg_20210914_0600.grib2"
dataset = open_url(url)
dataset = open_url(url, default_charset="utf-8")
```
both give
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 15683: ordinal not in range(128)
```
and the current traceback
```
>>> dataset = open_url(url, default_charset="utf-8")
Traceback (most recent call last):
File "<stdin>", line 1, in …
```
=> WIP: add user_charset arg

.github/workflows/python.yml, src/pydap/model.py, src/pydap/responses/das.py, src/pydap/tests/test_model.py
Fixes #203 
Import ABC from collections.abc instead of collections for Python 3 compatibility.
This is the same as #210. Resubmitting it as a new PR to get GitHub actions CI to run on it.
=> Import ABC from collections.abc instead of collections for Python 3 compatibility

pytest.ini
Fixes #245 
Fix warnings by registering our custom pytest test markers.
=> fixed pytest warnings

.github/workflows/python.yml, .github/workflows/python_macos.yml, .gitignore, src/pydap/handlers/dap.py, src/pydap/tests/test_responses_error.py
Fixing a typo that was causing the client to attempt to build a DAS in a DAP4 context.
This PR also drops testing for Python 3.6, 3.7, and 3.8. The OS-X tests remain at 3.7 , to be sorted another day.
Some baseline regex had to be updated for newer Python behavior.
=> DAP4/DAS Patch

.github/workflows/publish_to_pypi.yml, setup.py
This PR fixes a couple of things that were overlooked (and not really testable) in the previous PR for the workflow to publish to PyPI:
* The `python_version` in the `setup-python` action needed to be a string.
* PyPI didn't like the format of the `long_description`. This required ensuring new enough versions of some dependencies and then also specifically telling `setup.py` that the `long_description` was Markdown content type.
This workflow has now successfully run, so [pydap==3.4.0](https://pypi.org/project/pydap/) is now available. :tada:
=> Hackfest addendum

CONTRIBUTORS.md, src/pydap/__init__.py
This PR updates the version as tracked in `src/pydap/__init__.py`, which is used when publishing to PyPI. It also updates `CONTRIBUTORS.md` to include myself and @jgliss, as well as organises the list back to being alphabetical.
=> Version bump for release 3.4.1

.github/workflows/run_tests_macos.yml, .github/workflows/run_tests_ubuntu.yml
This PR makes a few really small changes to the GitHub workflows that run tests:
* Renames the files containing the workflows:
* `python.yml` becomes `run_tests_ubuntu.yml`.
* `python_macos.yml` becomes `run_tests_macos.yml`.
* The following condition has been removed from several workflow steps: `if: success() || failure()`. This would force a step to run even if a preceding step failed. These workflows install packages that must be successfully installed for the tests to run, so the later steps should not run on failure (I _think_).
* ~~Updating the MacOS Python versions that the tests run on to align with the Ubuntu workflow.~~ I reverted this change as the tests fail on 3.8+. I'll try and determine why in a later PR.
I did also consider trying to consolidate the workflows into a …
=> Clean up test workflows.

.github/workflows/run_tests_macos.yml, src/pydap/server/devel.py, src/pydap/server/devel_ssl.py, src/pydap/tests/test_server_devel.py, src/pydap/tests/test_server_devel_ssl.py
This PR 
There was an earlier effort to update the python versions for testing workflow on #283. This PR essentially allows that to happen. However, this PR does not address the issue raised in #292 with `multiprocessing.Process and netcdf`. But it allows for updated testing workflow by skipping tests that may fail on MacOS (there is no issue on Ubuntu / linux). A separate PR should address #292.
Suggestions are welcome. This can also be a draft PR, but I do think that there is merit in updating the testing (python) environment, while also identifying the issues with MacOS and Windows
=> Allow newer python versions to test on MacOS mimicking Ubuntu workflows

.github/workflows/pre-commit.yml, .github/workflows/run_tests_macos.yml, .pre-commit-config.yaml, src/pydap/tests/dap_4_access/dap4_access_test.py
=> set up pre-commit on github actions

README.md, pyproject.toml, src/pydap/tests/test_wsgi_app.py, src/pydap/wsgi/app.py
The following Pull Request is a continuation of PR #286 started by @raphaeljolivet (Thanks for the contribution!)
```python
>>> pydap -h
A file-based pydap server running on Gunicorn.
Usage:
pydap [options]
Options:
-h --help                     Show this help message and exit
--version                     Show pydap version
-i --init DIR                 Create directory with templates
-b ADDRESS --bind ADDRESS     The ip to listen to [default: 127.0.0.1]
-p PORT --port PORT           The port to connect [default: 8001]
-d DIR --data DIR             The directory with files [default: .]
-t DIR --templates DIR        The directory with templates
--workers INT                 Number of workers [default: 1]
--threads INT                 Number of threads [default: 1] …
```
=> Fixes #207: Pydap can now use PasterApp and serve data 

pyproject.toml, pytest.ini, src/pydap/model.py, src/pydap/tests/test_model.py, src/pydap/tests/test_server_devel_ssl.py
The reasoning behind muting Deprecation warnings is that these show up in many packages that have pydap as a dependency, for example [dfm_tools#803](https://github.com/Deltares/dfm_tools/issues/803), and that many of these Deprecation Warnings come from pydap internally (producing DeprecationWarnings, and failing to capture some other warnings).
Feel free to suggest a different approach to filtering these warnings.
=> Removes deprecation warnings

src/pydap/handlers/dap.py, src/pydap/model.py, src/pydap/parsers/dmr.py, src/pydap/responses/dmr.py, src/pydap/tests/data/dmrs/SWOT_GPR.dmr, src/pydap/tests/test_parsers_dap.py, src/pydap/tests/test_parsers_dmr.py, src/pydap/tests/test_responses_dmr.py
In the example in #326, now:
```python
url = "dap4://oceandata.sci.gsfc.nasa.gov/opendap/PACE_OCI/L3SMI/2024/0301/PACE_OCI.20240301_20240331.L3m.MO.CHL.V2_0.chlor_a.0p1deg.NRT.nc"
ds = open_url(url)
ds['chlor_a']
>>> <BaseType with data Dap4BaseProxy()...>
```
And ```ds.tree()``` yields:
```python
.PACE_OCI.20240301_20240331.L3m.MO.CHL.V2_0.chlor_a.0p1deg.NRT.nc
├──lat
├──lon
├──chlor_a
├──palette
├──rgb
└──eightbitcolor
```
A much simpler `pydap` dataset model in DAP4. 
Am I correctly interpreting one of many differences between DAP4 & DAP2 @jgallagher59701 ?
=> Simplify the Dataset model in DAP4

src/pydap/model.py, src/pydap/tests/test_model.py
With this PR one can do this:
```python
url = 'http://test.opendap.org:8080/opendap/podaac/LLC4320_pre-SWOT_Yongala_20121001.nc'
ds = open_url(url, protocol='dap4')
ds.nbytes
>>> 2448965660
```
This value is for uncompressed numpy array data. And so is much larger (almost 6x) than the value reported in the DAP Response Form: [445456145](http://test.opendap.org:8080/opendap/podaac/contents.html)
=> include numpy attributes to BaseType to compute arraysize in bytes (uncompressed)

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/pre-commit.yml, .github/workflows/run_tests_macos.yml, .github/workflows/run_tests_ubuntu.yml, .pre-commit-config.yaml, pyproject.toml
=> Point to `main` branch on GH/workflows

src/pydap/handlers/dap.py, src/pydap/lib.py, src/pydap/parsers/__init__.py, src/pydap/tests/test_client.py, src/pydap/tests/test_handlers_dap.py, src/pydap/tests/test_lib.py, src/pydap/tests/test_parsers.py
Selections are not entirely being parse appropriately in DAP4. The work to enable that will be separate.
=> correctly parse projections (CEs) with Arrays in DAP4

ci/environment.yml, pyproject.toml, pytest.ini, src/pydap/handlers/csv/__init__.py, src/pydap/handlers/dap.py, src/pydap/handlers/lib.py, src/pydap/handlers/netcdf/__init__.py, src/pydap/lib.py, src/pydap/responses/lib.py, src/pydap/responses/version.py, src/pydap/tests/test_handlers_lib.py, src/pydap/wsgi/app.py, src/pydap/wsgi/ssf.py
- Migrates away from the deprecated `pkg_resources` and adds `importlib-metadata` and `importlib-resources`, which remain compatible with Python 3.9. In the near future (when Python 3.9 is no longer actively maintained), we can drop these new dependencies. In theory we should be able to replace them with`importlib.metadata` and `importlib.resources` with very minimal syntax changes (`importlib is already included within `setuptools`, but changed behavior starting with Python 3.10).
Broadly,
=> Implicit discovery of entry points

src/pydap/parsers/dmr.py, src/pydap/responses/dmr.py, src/pydap/tests/data/dmrs/SimpleGroup.dmr, src/pydap/tests/datasets.py, src/pydap/tests/test_parsers_dmr.py, src/pydap/tests/test_responses_dmr.py
=> correctly define `named dimensions` at `root` level

src/pydap/model.py, src/pydap/tests/datasets.py, src/pydap/tests/test_model.py
This PR allows the following syntax for generating DAP object through Fully Qualifying Names (for more, see #361)
```python
RootGroup = DatasetType("example dataset", dimensions={"time":1, "nv":2})
RootGroup.createGroup("SimpleGroup", dimensions = {"Y": 4, "X": 4})
RootGroup.createVariable("/SimpleGroup/Temperature", np.arange(10, 26, 1, dtype="f4").reshape(1, 4, 4), dims=("/time", "/SimpleGroup/Y", "/SimpleGroup/X"))
RootGroup.createSequence("/location")
RootGroup.createVariable("/location.lat")
RootGroup.createVariable("/location.lon")
RootGroup.createVariable("/location.elev")
RootGroup.createSequence("/location.time_series")
RootGroup.createVariable("/location.time_series.time")
RootGroup.createVariable("/location.time_series.wind") …
```
=> Creates method to generate dap objects

src/pydap/handlers/dap.py, src/pydap/lib.py, src/pydap/model.py, src/pydap/parsers/dmr.py, src/pydap/responses/dmr.py, src/pydap/tests/data/dmrs/SimpleGroup.dmr, src/pydap/tests/datasets.py, src/pydap/tests/test_model.py, src/pydap/tests/test_parsers_dmr.py, src/pydap/tests/test_responses_dmr.py, src/pydap/tests/test_responses_html.py
With regards to issue #374 the example described there now yields (correctly):
```python
pds['/gt1r'].attributes
```
```python
{'Description': 'Each group contains the segments for one Ground Track. As ICESat-2 orbits the earth, sequential transmit pulses illuminate six ground tracks on the surface of the earth.  The track width is approximately 14m.  Each ground track is numbered, according to the laser spot number that generates a given ground track.  Ground tracks are numbered from the left to the right in the direction of spacecraft travel as: 1L, 1R in the left-most pair of beams; 2L, 2R for the center pair of beams; and 3L, 3R for the right-most pair of beams.',
'atlas_pce': 'pce3',
'atlas_beam_type': 'strong',
'groundtrack_id': …
```
=> get Dap objects function and a fix 

src/pydap/handlers/netcdf/__init__.py, src/pydap/parsers/dmr.py, src/pydap/responses/dmr.py, src/pydap/tests/datasets.py, src/pydap/tests/test_handlers_netcdf.py, src/pydap/tests/test_responses_html.py
on a local environment.~ A test was removed, because despite passing a protocol='dap4' to the DapHandler, the `ServerSideFunction` did not recognize this and attempted to set up a dap2 contraint expression when subsetting the local file. This is a subject of a separate issue/PR (minimal priority).
=> removes GridType from netcdf handler

src/pydap/handlers/dap.py
This is a quick patchwork so that pydap CAN parse DAP4 responses from TDS.  See #401 
There are a couple of issues related to parsing DAP responses from a TDS. This PR solves:
a) Correctly split DMR from binary data in the response. There are very small differences in how the 2 servers split the dmr from the binary data:
```
"... </Dataset>\n\r\n<binary data>"
```
```
"... </Dataset>\r\n<binary data>"
```
DAP4 support within pydap has been written to accomodate Hyrax. The vary small difference between the two servers means that returning data from a TDS via DAP4 results in error.
With this PR, now there is no error but there is a "UserWarning" to inform users to use DAP2 protocol with TDS. The reason for that is this PR still does not fix another discrepancy between TDS and Hyrax servers. …
=> Quick patchwork to parse TDS DAP4 responses

src/pydap/parsers/dmr.py, src/pydap/tests/test_parsers_dmr.py
```python
url = 'http://test.opendap.org:8080/opendap/data/nc/123bears.nc'
ds = open_url(url, protocol='dap4')
ds.tree()
```
yields now:
```
.123bears.nc
├──i
├──j
├──order
├──shot
├──aloan
├──cross
├──l
└──bears
```
where bears is a String array as denoted in the [dmr](http://test.opendap.org:8080/opendap/data/nc/123bears.nc.dmr)
=> add functionality to parse dmr with String variables

src/pydap/parsers/dmr.py, src/pydap/responses/dmr.py, src/pydap/tests/data/dmrs/SimpleGroup.dmr, src/pydap/tests/datasets.py, src/pydap/tests/test_parsers_dmr.py, src/pydap/tests/test_responses_dmr.py, src/pydap/tests/test_responses_html.py
~This is a draft~
This is included in the testing
```python
dmr = """
<Dataset name="foo">\n
<Int32 name="x">\n
<Attribute name="attr" type="Float32">\n
<Value></Value>\n
<Value>2</Value>\n
<Value value="1"/>\n</Attribute>\n
</Int32>\n
</Dataset>
"""
dom_et = DMRParser(dmr).node
dataset = DMRParser(dmr).init_dataset()
variables = get_variables(dom_et)
get_attributes(variables['x']['element'])['attr']
```
the last line returns the list for attribute `'attr'`. All values, excep None, are Float32, associated with variable `'x'` of type int32
```python
[None, 2.0, 1.0]
```
=> broaden dmr parser to allow multiple values on single attribute

src/pydap/client.py, src/pydap/handlers/dap.py, src/pydap/tests/test_handlers_dap.py, src/pydap/tests/test_parsers_dap.py, src/pydap/tests/test_parsers_dmr.py
The following Pull Request: ~(DRAFT)~
a new feature, etc.
Splits the dap response into dmr (first chunk) and data in a generic way, taking into account the first 4 bytes of the response.
=> Decode chunk header to set length of DMR in a generic way and endianness of data

src/pydap/cas/urs.py, src/pydap/client.py, src/pydap/handlers/dap.py, src/pydap/net.py, src/pydap/server/devel.py, src/pydap/server/devel_ssl.py, src/pydap/tests/test_net.py, src/pydap/tests/test_server_devel_ssl.py
In essence, this PR makes it so that 
- `pydap.net.GET` uses `requests.get(URL)` when the `application is None`, meaning that the URL points to a remote dataset. 
- `pydap.net` uses `Webob.Request.get_response` When application is not None, but intead is a wsgi applicatoin wrapping a pydap dataset. This case is mostly use for testing/development purposes.
=> Drop Webob from client use of pydap

src/pydap/model.py, src/pydap/tests/test_model.py
```python
url = "http://test.opendap.org/opendap/data/nc/coads_climatology.nc"
pyds = open_url(url, protocol="dap2")
pyds.tree()
.coads_climatology.nc
├──COADSX
├──COADSY
├──TIME
├──SST
│  ├──SST
│  ├──TIME
│  ├──COADSY
│  └──COADSX
├──AIRT
│  ├──AIRT
│  ├──TIME
│  ├──COADSY
│  └──COADSX
├──UWND
│  ├──UWND
│  ├──TIME
│  ├──COADSY
│  └──COADSX
└──VWND
├──VWND
├──TIME
├──COADSY
└──COADSX
#=========================== this is new
pyds.grids()
>>>{'SST': {'shape': (12, 90, 180), 'maps': ['TIME', 'COADSY', 'COADSX']},
'AIRT': {'shape': (12, 90, 180), 'maps': ['TIME', 'COADSY', 'COADSX']},
'UWND': {'shape': (12, 90, 180), 'maps': ['TIME', 'COADSY', 'COADSX']},
'VWND': {'shape': (12, 90, 180), 'maps': ['TIME', 'COADSY', 'COADSX']}} …
```
=> adds .grids() to identify all grid objects within dataset

src/pydap/handlers/dap.py, src/pydap/tests/test_handlers_dap.py
(see description in #450 )
```python
url ="dap2://test.opendap.org/opendap/data/nc/coads_climatology.nc"
pyds = open_url(url) # this works now!
```
=> replace dap2 to http when using schema to determine dap protocol

.gitignore, src/pydap/client.py, src/pydap/model.py, src/pydap/tests/test_client.py, src/pydap/tests/test_model.py
```python
url = "http://<data_url>"
pyds = pydap.client.open_url(url, use_cache=True)
session=pyds.session
```
And so the session can be reused to talk to a different server, and cache that response. It will not prevent the unexpected behavior described in #444 , but it will make it easier to avoid it or to correct it with:
```python
session.cache.clear()
```
=> include a session object as attribute to pydap.dataset so that it can be retrieved/recovered by user

src/pydap/client.py, src/pydap/handlers/dap.py, src/pydap/tests/test_client.py
~DRAFT PR~
This PR will enable
For example:
Consider dimensions: 'time', 'lat', 'lon', 'Z' all appear in each of the `N` urls that make up the collection. When requesting the `dap` response of the array `time`, it will no longer be downloaded N times. It will instead it is only downloaded once. Same for each of the other dimensions.
The following is an example of how it works:
```python
fom pydap.net import create_session
new_session = create_session(use_cache=True)
urls[:5]
>>>
['dap4://oceandata.sci.gsfc.nasa.gov/opendap/PACE_OCI/L3SMI/2024/0305/PACE_OCI.20240305.L3m.DAY.CHL.V3_0.chlor_a.4km.nc?dap4.ce=/lat;/lon;/chlor_a',
'dap4://oceandata.sci.gsfc.nasa.gov/opendap/PACE_OCI/L3SMI/2024/0306/PACE_OCI.20240306.L3m.DAY.CHL.V3_0.chlor_a.4km.nc?dap4.ce=/lat;/lon;/chlor_a', …
```
=> enables caching of multiple dap4 urls and custom cache key for dimensions dap responses

README.md, docs/en/how_to_install.md, docs/en/intro.md, docs/en/responses.rst, docs/en/server.rst, pyproject.toml
Hi there,
I use `pydap` on Anaconda, and I noticed that Python3.13 has recently received support here. I just wanted to be certain that the metadata reflects that change.
There also were a handful of small formatting, consistency, and spelling issues that I figured could be fixed at the same time.
Cheers,
=> Add Python3.13 metadata and fix spelling mistakes

src/pydap/handlers/dap.py, src/pydap/net.py, src/pydap/tests/test_client.py, src/pydap/tests/test_open_dap4_url.py, src/pydap/tests/test_server_devel_ssl.py
This PR makes the `https` the default url scheme to revert into, when a data user uses the URL scheme to define the DAP protocol.
User provides following url that specifies the DAP4 protocol:
```python
url = "dap4://<rest_of_data_url>" # pydap will download dmr
url = "dap2://<rest_of_data_url>" # pydap will download dds and das
```
Internally, `pydap` then sets `protocol="dap4"` (or `protocol='dap2'`) and will revertsthe scheme of the provided url to:
```python
url = "http://<rest_of_data_url>"
```
pydap then uses the requests library to `GET` dmrs and dap responses. I have paid close attention to the redirects, and there is a 301 redirect (permanently moved) which then leads to the following url
```python
"https://<rest_of_data_url>" # with relevant suffix appended here
```
This is …
=> set `https` as the default url scheme when dap2 or dap4 are used to set

src/pydap/responses/dds.py
This does not show up during testing, because it represents the case when reading data from an nc- file (as opposed to pydap dataset created for testing purposes)
Now the dds looks like:
```python
Dataset {
Float64 lon_bnds[lon = 180][bnds = 2];
Float64 lat_bnds[lat = 170][bnds = 2];
Float64 time_bnds[time = 24][bnds = 2];
Float32 tos[time = 24][lat = 170][lon = 180];
Float64 lon[lon = 180];
Float64 lat[lat = 170];
Float64 time[time = 24];
} tos_O1_2001-2002%2Enc%2Enc4;
```
and accessing using pydap now looks like:
```python
open_url("http://127.0.0.1:8001/tos_O1_2001-2002.nc.nc4").tree()
.tos_O1_2001-2002.nc.nc4
├──lon_bnds
├──lat_bnds
├──time_bnds
├──tos
├──lon
├──lat
└──time
```
=> Remove slashes from dimension names when creating dds responses (pydap server)

src/pydap/client.py, src/pydap/tests/test_client.py
###
This PR greatly reduces the number of dap responses pydap needs to download in the case multiple (N) urls that aggregate along a dimension `concat_dim` (in most cases, `time`). 
The specific scenario is when the length of the `concat_dim` > 1. In that scenario, `3` dap responses per `concat_dim` per URL are downloaded (Xarray feature when aggregating multiple urls).
This PR makes it so that only `3` dap responses (total!) are downloaded for the `concat_dim` array (e.g. `time`). This is accomplished by forcing the download of all DMR (metadata). This is possible because of the internals of Xarray.
This code assumes that all remote data have the same dimension and identical dim shapes.
Consider a year of MERRA-2 data.
```python …
```
=> Improves support for concat_dims with size larger than 1

src/pydap/client.py, src/pydap/net.py, src/pydap/tests/test_client.py
Enables more flexibility when caching dap responses.
`a)` After running `consolidated_metadata`, one can reuse the session with a mix of using its cached urls (dimensions), and not caching dap responses (when downloading dap responses of variables that are NOT dimensions or maps)
`b)` enables downloading + caching responses when not using `consolidated_metadata`
=> enables caching when consolidated-metadata is not run

src/pydap/handlers/dap.py
- Enables, if installed, the use of `httpx` to download dap responses. 
`httpx` is:
- Modern python http client (more than requests)
- Async / http/2 support
- Almost identical syntax to Requests
`httpx` will NOT be listed as a dependency (not even optional) but if installed and if the response is from a `httpx` client, the class `UNPACKDAP4DATA` can decode the `dap response` and return a correct `BaseType` data array
With some few download testing I have done, the first download using the `httpx` client is 1-3x faster than using `requests`. At worst, it the the same speed, but can be significantly faster.
This small change in the code will enable further benchmarking download timings on PR #525
=> Enable unpacking responses from httpx

src/pydap/client.py, src/pydap/lib.py, src/pydap/model.py, src/pydap/tests/test_client.py, src/pydap/tests/test_lib.py, src/pydap/tests/test_model.py, src/pydap/tests/test_open_dap4_url.py
improves how `consolidate_metadata` downloads dap responses: batching several variables within a single dap url (before 1 dap url per variable), since this is how xarray handles / downloads arrays in dap4. Now that I am changing how xarray handles dap downloads (can download multiple variables within same dap url), this will support that change. 
a new feature, etc.
Consider the case of OSCAR data (collection). In this case, there are 2 named dimensions (`latitude` and `longitude`), a dimension array (`time`) and two Maps: `lat` and `lon`. `lat` and `lon` are shared across all granules (this is level 3/4 data). To avoid re-download repeated data we need to specify these `lat` and `lon` arrays, so that these are only downloaded once. …
=> Improve handling of Maps when consolidating metadata

src/pydap/net.py
With this, the following works
```python
import earthaccess
from pydap.net import create_session
auth = earthaccess.login(strategy="interactive", persist=True)
_session = earthaccess.get_requests_https_session()
session = create_session(session=_session)
```
And so a user can make of of `earthaccess` for token extraction from NASA in the background rather than manually having to store across session as previously described in the documentation or jupyter notebooks on the binder
=> enable updating the session credentials from a different session

src/pydap/client.py, src/pydap/handlers/dap.py, src/pydap/lib.py, src/pydap/model.py
This will enable to
- Construct dap urls following the shared-dimensions spec (knowledge of dimensions slices, and all variables in the metadata dmr) from the original provided url (which already may contain a constraint expression).
-  Download in parallel all the dap responses
=> Enable `shared dimensions` option on when consolidated data

.github/workflows/run_tests_macos.yml, .github/workflows/run_tests_ubuntu.yml, src/pydap/client.py, src/pydap/model.py, src/pydap/net.py, src/pydap/tests/test_client.py, src/pydap/tests/test_lib.py, src/pydap/tests/test_open_dap4_url.py
- This PR attempts to address the failures that arise in on github workflows, for example :
```python
for name, variable in variables.items():
for dim in variable["dims"]:
if dim in variables.items():
variable["shape"] += (variables[dim]["size"],)
else:
>                   variable["shape"] += (named_dimensions[dim],)
^^^^^^^^^^^^^^^^^^^^^
E                   KeyError: '/SLP/'
src/pydap/parsers/dmr.py:274: KeyError
=========================== short test summary info ============================
FAILED src/pydap/tests/test_lib.py::test_get_batch_data_sliced_nondims[[http://test.opendap.org/opendap/dap4/SimpleGroup.nc4.h5-/SimpleGroup-/SimpleGroup/Salinity-Temperature-key3-/SimpleGroup/Salinity[0:1:0][0:1:39][0:1:39]-expected_shape3](http://test.opendap.org/openda …
```
=> remove global url definitions - make tests self contained

src/pydap/client.py, src/pydap/handlers/dap.py, src/pydap/tests/test_client.py
This now again works smoothly (database construction) 
```python
consolidate_metadata(urls, concat_dim='time', session=session)
```
where len(urls)=217. It took 1 min and 30 secs. It downloaded ~400 urls (mostly all dmrs).
And now
```python
ds = xr.open_mfdataset(
urls,
engine='pydap',
session=session, # reuse database as session
parallel=True,
combine='nested',
concat_dim='time',
)
```
Takes ~ 2-5 sec every time, all or it parsing and reusing the database. There is no longer any download at this point.
Without `consolidate_metadata` it took 40 minutes before a TimeOut Error (never completed), during which time it requested upwards ~ 1500 requests, the vast majority of which were individual dap responses (repeated / identical dimensions, one per granule)
=> use `GET` instead of shared session

src/pydap/client.py, src/pydap/handlers/dap.py, src/pydap/net.py, src/pydap/tests/test_client.py
@jgallagher59701  Ready for review. The following example works well:
consider the following list of dap4 urls of the form
```python
dap4://opendap.earthdata.nasa.gov/providers/POCLOUD/collections/ECCO%20Ocean%20Temperature%20and%20Salinity%20-%20Monthly%20Mean%20llc90%20Grid%20(Version%204%20Release%204)/granules/OCEAN_TEMPERATURE_SALINITY_mon_mean_1999-12_ECCO_V4r4_native_llc0090?dap4.ce=/THETA;/SALT;/k;/tile;/j;/i;/time
```
This granule has 5 dimension, and consider the case where I want to aggregate a list of 217 such granules along the time dimension. So URLS is a list of 217 elements
```python
%%time
consolidate_metadata(URLs, concat_dim='time', session=session) # batch=False by default
>>> CPU times: user 2.66 s, sys: 955 ms, …
```
=> Enable batch=False|True when consolidating metadata

src/pydap/client.py, src/pydap/tests/test_client.py
```python
get_cmr_urls(ccid = "concept_collection_id")
get_cmr_urls(doi = "doi_of_collection")
```
In addition to the options below, the following is possible
```python
get_cmr_urls(short_name="short_name_collection", version=["v01", "v02",  "v04"])
```
searches for various versions of the same collection, returning all possible urls. This is nice, because it enables the user to filter a collection based on its version. This is equivalent to searching 3 different collections.
=> get_cmr url: enable seaching using version and shortname
